# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
# No skiptest in 2.6 so ignore for now
#  - "2.6"
  - "2.7"

install:
  - "pip install ."

script:
# Run the unit tests for bcftbx
  - "python setup.py test"
# Run the make_macs2_xls tests
  - "nosetests --exe -v ChIP-seq/make_macs2_xls.py"
# Run the fastq_strand tests
  - "nosetests --exe -v QC-pipeline/fastq_strand.py"
# Run the best_exons example
  - "cd microarray/examples/"
  - ./test_best_exons.sh